class Main
{
	public static void main(String[] args) {
	    try{
	        int dividebyzero=5/4;
	        System.out.println("Rest of code in try block");
	    }
	    catch(ArithmeticException e){
	        System.out.println("ArithmaticExeption="+e.getMessage());
	    }
	    finally{
	        System.out.println("This is the finally block");
	    }
		
	}
}
